# Generated by Django 5.0.3 on 2024-03-26 11:49

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=20)),
                ('fatherPhone', models.CharField(max_length=20)),
                ('motherPhone', models.CharField(max_length=20)),
                ('fatherPicture', models.ImageField(upload_to=account.models.get_image_path)),
                ('motherPicture', models.ImageField(upload_to=account.models.get_image_path)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('subCode', models.CharField(max_length=70)),
                ('maxClass', models.IntegerField()),
                ('hasExam', models.BooleanField(default=True)),
                ('credit', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=20)),
                ('fatherPhone', models.CharField(max_length=20)),
                ('motherPhone', models.CharField(max_length=20)),
                ('fatherPicture', models.ImageField(upload_to=account.models.get_image_path)),
                ('motherPicture', models.ImageField(upload_to=account.models.get_image_path)),
                ('experience', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=10)),
                ('isMarried', models.BooleanField()),
                ('partnerName', models.CharField(blank=True, max_length=100)),
                ('partnerPhone', models.CharField(blank=True, max_length=20)),
                ('partnerPicture', models.ImageField(blank=True, upload_to=account.models.get_image_path)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('session', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('subjects', models.ManyToManyField(to='account.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('permissions', models.ManyToManyField(to='account.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('studentNumber', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to=account.models.get_image_path)),
                ('mobile', models.CharField(max_length=10)),
                ('isDeleted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.batch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=10)),
                ('EmpId', models.IntegerField()),
                ('picture', models.ImageField(upload_to=account.models.get_image_path)),
                ('mobile', models.CharField(max_length=10)),
                ('isDeleted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.batch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.teacherdetails')),
            ],
        ),
    ]
